import Head from 'next/head'
import styles from '../styles/Home.module.css'

import type { NextPage } from 'next'
import Image from 'next/image'
import React from 'react'
import { FormEvent, useState } from 'react'
import { IHeroiOB } from '../types/iHeroiOB'
import { IHeroi } from '../types/iHeroi'
import { consultaApiHerois } from '../services/consultarApiHerois'
import { updateSimulator } from '../services/updateHeroi'



const Bomb = () => {

    const [carteira, setCarteira] = useState('')
    const [heroi, setHeroi] = useState([])

    const onSubmit = (e: FormEvent) => {
        e.preventDefault();
    }

    const buscarHero = async () => {
        console.log("clicou no botao")

        const heroi: any = await calcular(carteira)
        setHeroi(heroi)

    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Bomb Simulator</title>
                <meta name="description" content="Generated by gbs" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <main className={styles.main}>

                <h1 className={styles.title}>
                    simulator
                </h1>

                <p className={styles.description}>
                    <label htmlFor="carteira">carteira: </label>
                    <input type="text" name="carteira" id="carteira" placeholder="numero da carteira" 
                        onChange={(e) => { setCarteira(e.target.value) }}
                    />
                </p>

                <div className={styles.card}>

                    <Image onClick={buscarHero}
                        src="/hero.png"
                        alt="hero"
                        width={70}
                        height={93}
                        quality={100}
                    />
                </div>
                herois: {heroi?.length}
                <div className={styles.grid}>
                        {heroi?.map((item: IHeroiOB) => 
                             <div key={item.id} className={styles.card}>
                                <div>{item.id} </div>
                                <div>{item.rarity} - level: {item.level}</div>

                                <div>{item.skin}</div>
                                <div>Power: {item.power}</div>
                                <div>Speed: {item.speed}</div>
                                <div>Stamina: {item.stamina}</div>
                                <div>Bomb num: {item.bombnum}</div>
                                <div>Pombo range: {item.bombrange}</div>
                                ---------------------------------
                                <div>Max profit: {item.maxProfit}</div>
                                <div>Min profit: {item.minProfit}</div>
                                <div>Avg profit: {item.avgProfit}</div>
                                <div>Total profit: {item.totalProfit}</div>
                            </div>
                        )}
                </div>
            </main>
        </div>

    )
}




const calcular = async (carteira: string) => {
    if (!carteira){
        return console.log("Ai, preencha o campo carteira")
    }

    var dados: Array<IHeroi> = await consultaApiHerois(carteira)
    console.log(dados);
    
        const final = dados?.map((item: IHeroi) => {
            return updateSimulator(item)
        })

        //console.log(final);
        
        return final
    
}

export default Bomb